### ISSUE TITLE
Typo in linux-stable_4.1.bb

### ISSUE THREAD

**Issue by allsey87** [jumpnow/meta-duovero#1]
The line: https://github.com/jumpnow/meta-duovero/blob/fido/recipes-kernel/linux/linux-stable_4.1.bb#L7

Should read: RDEPENDS_kernel-base += "kernel-devicetree"
Instead of: RDEPENDS_kernel_base += "kernel-devicetree"

This issue causes the device tree not to be deployed onto the image

**Comment by scottellis** [comment]
Travelling for next few days, but I'll take a look when I return.

I admit I've tested much more with the BBB then the Duovero, but I use the same syntax there and I switch between dtbs all the time. 

  https://github.com/jumpnow/meta-bbb/blob/fido/recipes-kernel/linux/linux-stable_4.1.bb

What exactly is not getting deployed?

**Comment by allsey87** [comment]
The default dtb isn't deployed automatically into the /boot directory in
the rootfs. You probably didn't notice though as your script rootfs.sh
manually copies your dtb's in afterwards...

Scott Ellis <notifications@github.com> schrieb am Do., 6. Aug. 2015 12:14:

**Comment by scottellis** [comment]
Applied. Thanks.
